import { RULESET_SIMPLIFY_TEXT } from "./text"
import { RULESET_SIMPLIFY_QUANTITY } from "./quantity"
import { RULESET_SIMPLIFY_MATH } from "./math"
import { RULESET_SIMPLIFY_STACK_OVERFLOW } from "./stackOverflow"

export { RULESET_SIMPLIFY_TEXT } from "./text"
export { RULESET_SIMPLIFY_QUANTITY } from "./quantity"
export { RULESET_SIMPLIFY_MATH } from "./math"
export { RULESET_SIMPLIFY_STACK_OVERFLOW } from "./stackOverflow"

// export const RULESETS_SIMPLIFY = [RULESET_SIMPLIFY_TEXT, RULESET_SIMPLIFY_QUANTITY, RULESET_SIMPLIFY_MATH, RULESET_SIMPLIFY_STACK_OVERFLOW]
export const RULESETS_SIMPLIFY = [RULESET_SIMPLIFY_TEXT, RULESET_SIMPLIFY_QUANTITY, RULESET_SIMPLIFY_MATH, RULESET_SIMPLIFY_STACK_OVERFLOW]
